Set build_timestamp for distribution trees
For some distribution trees, their build timestamp is the only way
to identify them uniquely. Repositories like CentOS 8 BaseOS, Appstream,
PowerTools, HighAvailability, all use the same distribution tree name and release.

For migration/stages pipeline to work correctly, each Artifact of multi-artifact
content needs its ContentArtifact which is created at ContentSaver stage only for
non-saved content.
If the build timestamp is not set and distribution trees are not uniquely identified,
depending on the order of migration, some images might be without a ContentArtifact
which will lead to the migration error:
ValueError: No declared artifact with relative path ".treeinfo" for content "<DistributionTree: pk=...>".

closes #8566
https://pulp.plan.io/issues/8566

Required PR: https://github.com/pulp/pulp_rpm/pull/2002
(Alternatively, just downgrade your productmd to 1.32.)